### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by LiveRock** [PsychTechApS/flutter_menu#6]
HI

Looking at the description and demo; looks great!
But my Flutter projects is null safety enabled and I can't build with current version of flutter_menu.
Any plans to make it null safety ready?
Thanks!

**Comment by Dorbmon** [comment]
Anything new about this?

**Comment by PsychTechApS** [comment]
I have been away from Flutter the last 3 months working on svelte.js projects instead, but I will consider finishing the upgrade to null safety if the demand is high enough.

**Comment by syedecryptr** [comment]
+1

**Comment by PsychTechApS** [comment]
The package has been updated to null safety at this moment. Thank you @syedecryptr  for your help with this 👍
